# Generated by Django 5.1.2 on 2026-04-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_postmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postmodel",
            name="image",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="profile_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
